export const message = {
  WRONG_SYNTAX: 'Validator Error',
  TEXT_WRONG_LOGIN: 'Username hoặc Password không đúng',
  USER_NOT_EXIST: 'Không tồn tại tên tài khoản',
  WRONG_PASS: 'Mật khẩu không đúng',
  REGISTER_SUCCESS: 'Đăng ký thành công',
  RE_PASS: 'Mật khẩu chưa trùng khớp',
  VALIDATOR_ERR: 'Validator Error',
  VALIDATOR_ERR2: 'Thiếu trường hoặc không đúng định dạng',
  UPDATE_PERMISSION_SUCCESS: 'Cập nhật quyền thành công',
  UPDATE_PERMISSION_FALIL: 'Cập nhật quyền thất bại',
  UPDATE_PASSWORD_SUCCESS: 'Cập nhật mật khẩu thành công',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  DELETE_USER_SUCCESS: 'Xoá tài khoản thành công',
  B1_CONFIRM: 'Hoàn thành khai báo',
  TIME_SET_SUCCESS: 'Cấp thời gian khai báo thành công',
  TIME_SET_FAIL: 'Cấp thời gian khai báo thất bại',
  TIME_INVALID: 'Vui lòng chọn khoảng thời gian khai báo hợp lệ',
  DELETE_UNIT_SUCCESS: 'Xóa đơn vị thành công',
  DELETE_UNIT_FAIL: 'Xóa đơn vị thất bại',
};
